import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Customer } from '@shared/types';
import { format } from 'date-fns';

export function generateCheckoutReport(checkedOutCustomers: Customer[], hotelName?: string) {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(hotelName || 'Hotel Management System', 20, 20);
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.text('Checkout Report', 20, 35);
  
  doc.setFontSize(12);
  doc.text(`Generated on: ${format(new Date(), 'MMM dd, yyyy hh:mm a')}`, 20, 45);
  doc.text(`Total Checked Out Guests: ${checkedOutCustomers.length}`, 20, 55);
  
  // Prepare data for table
  const tableData = checkedOutCustomers.map((customer, index) => [
    index + 1,
    customer.name,
    customer.aadharNumber || 'N/A',
    customer.phone,
    customer.email || 'N/A',
    customer.roomNumber,
    customer.roomTypeName,
    `₹${customer.roomPrice}`,
    format(new Date(customer.checkinTime), 'MMM dd, yyyy'),
    customer.checkoutTime ? format(new Date(customer.checkoutTime), 'MMM dd, yyyy') : 'N/A',
    customer.expectedStayDays ? `${customer.expectedStayDays} days` : 'N/A'
  ]);
  
  // Add table
  autoTable(doc, {
    head: [['S.No', 'Guest Name', 'Aadhar No.', 'Phone', 'Email', 'Room', 'Room Type', 'Rate/Night', 'Check-in', 'Check-out', 'Expected Stay']],
    body: tableData,
    startY: 70,
    styles: {
      fontSize: 8,
      cellPadding: 3,
      halign: 'center',
    },
    headStyles: {
      fillColor: [66, 139, 202],
      textColor: 255,
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245],
    },
    columnStyles: {
      0: { cellWidth: 15 }, // S.No
      1: { cellWidth: 25 }, // Name
      2: { cellWidth: 22 }, // Aadhar
      3: { cellWidth: 20 }, // Phone
      4: { cellWidth: 25 }, // Email
      5: { cellWidth: 15 }, // Room
      6: { cellWidth: 20 }, // Room Type
      7: { cellWidth: 18 }, // Rate
      8: { cellWidth: 20 }, // Check-in
      9: { cellWidth: 20 }, // Check-out
      10: { cellWidth: 18 }, // Expected Stay
    },
  });
  
  // Add summary at the bottom
  const finalY = (doc as any).lastAutoTable.finalY || 70;
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary:', 20, finalY + 20);
  
  doc.setFont('helvetica', 'normal');
  doc.text(`• Total Guests Checked Out: ${checkedOutCustomers.length}`, 20, finalY + 30);
  
  const totalRevenue = checkedOutCustomers.reduce((sum, customer) => {
    const stayDays = customer.expectedStayDays || 1;
    return sum + (customer.roomPrice * stayDays);
  }, 0);
  
  doc.text(`• Total Revenue from Checkouts: ₹${totalRevenue.toLocaleString()}`, 20, finalY + 40);
  
  // Room types breakdown
  const roomTypeCount = checkedOutCustomers.reduce((acc, customer) => {
    acc[customer.roomTypeName] = (acc[customer.roomTypeName] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);
  
  let yPosition = finalY + 50;
  doc.text('• Room Types:', 20, yPosition);
  Object.entries(roomTypeCount).forEach(([roomType, count]) => {
    yPosition += 10;
    doc.text(`  - ${roomType}: ${count} guests`, 25, yPosition);
  });
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Page ${i} of ${pageCount} | Generated by ${hotelName || 'Hotel Management System'}`,
      20,
      doc.internal.pageSize.height - 10
    );
  }
  
  return doc;
}

export function downloadCheckoutReport(checkedOutCustomers: Customer[], hotelName?: string) {
  const doc = generateCheckoutReport(checkedOutCustomers, hotelName);
  const fileName = `checkout-report-${format(new Date(), 'yyyy-MM-dd-HHmm')}.pdf`;
  doc.save(fileName);
}